MeuProjeto/MeuSite/MeuSite/MeuSite/curriculo/urls.py
from django.urls import path
from . import views

app_name = 'curriculo'

urlpatterns = [
    # essa rota pode ser acessada em /curriculo/spiff/
    # ou seja, /curriculo/ + spiff/
    # o link para essa rota pode ser criado usando o nome 'curriculo_spiff'
    # Exemplo: {% url 'curriculo:curriculo_spiff' %}
    path('spiff/', views.curriculo_spiff, name='curriculo_spiff'),
    # essa rota pode ser acessada em /curriculo/spiff/v2/
    path('spiff/v2/', views.curriculo_spiff_v2, name='curriculo_spiff_v2'),
]

MeuProjeto/MeuSite/MeuSite/urls.py
from django.contrib import admin
from django.urls import path
from MeuSite import views  
from django.urls import include
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home, name='home'), 
    path('curriculo/', include('curriculo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

MeuProjeto/MeuSite/curriculo/urls.py
from django.urls import path
from . import views

app_name = 'curriculo'
urlpatterns = [
    path('spiff/', views.curriculo_spiff, name='curriculo_spiff'),
    path('spiff/v2/', views.curriculo_spiff_v2, name='curriculo_spiff_v2'),
]

MeuProjeto/MeuSite/curriculo/models.py
from django.db import models

# Create your models here.

MeuProjeto/MeuSite/MeuSite/views.py
from django.shortcuts import render

def home(request):
    '''
    View function for home page of site.
    Renders the home.html template.
    '''
    return render(request, 'MeuSite/home.html')

MeuProjeto/MeuSite/curriculo/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def curriculo_spiff(request):
    '''
    View function for the astronaut Spiff's resume page.
    Renders the curriculo-v1.html template.
    This will display the resume page when the corresponding URL is accessed
    The curriculo_spiff view is responsible for displaying the content of the resume page
    It is a simple function-based view
    It takes a request object as a parameter
    It returns a rendered HTML response
    @param request: The HTTP request object
    @return: Rendered HTML response with resume page content
    '''
    return render(request, 'curriculo/curriculo-spiff.html')

@login_required
def curriculo_spiff_v2(request):
    '''
    View function for the astronaut Spiff's resume page version 2.
    A responsive version of the resume page.
    Renders the curriculo-v2.html template.
    This will display the resume page version 2 when the corresponding URL is accessed
    The curriculo_spiff_v2 view is responsible for displaying the content of the resume page version 2
    It is a simple function-based view
    It takes a request object as a parameter
    It returns a rendered HTML response
    @param request: The HTTP request object
    @return: Rendered HTML response with resume page version 2 content
    '''
    return render(request, 'curriculo/curriculo-spiff-v2.html')

MeuProjeto/MeuSite/MeuSite/templates/MeuSite/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
    <h1>Home Page do MeuSite</h1>

    <h2>Links para os currículos</h2>
    <ul>
        <li><a href="{% url 'curriculo:curriculo_spiff' %}">Currículo do Spiff</a></li>
        <li><a href="{% url 'curriculo:curriculo_spiff_v2' %}">Currículo responsivo do Spiff</a></li>
    </ul>
    <h2>Área de controle de acesso</h2>
    <ul>
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><form method='POST' action="{% url 'logout' %}">{% csrf_token %}<button type='submit'>Logout</button></form></li>
    </ul>
</body>
</html>

MeuProjeto/MeuSite/curriculo/templates/curriculo/curriculo-spiff-v2.html
<!DOCTYPE html>
<html lang="ptbr">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/meucurriculo.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Currículo - Marina Vidigal Nevares</title>
</head>
<body>
    <style>
        #foto{
    width: 200px
}
    </style>
    <main>
    <img id='foto' src="{% static 'img/fotocurriculo.jpg' %}" alt='Foto'>
    <h1>Marina Vidigal Nevares</h1>
    <h2>Resumo</h2>
        <p>Sou uma estudante de 18 anos cursando o segundo período de Engenharia de Produção na PUC-Rio. Conclui o ensino médio na Escola Parque Barra em 2024.</p>
    <h3>Disciplinas cursadas</h3>
        <table>
        <thead>
            <tr>
                <th>Código da disciplina</th>
                <th>Nome da disciplina</th>
                <th>Ano e semestre</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>CTC4002</td>
                <td>Modelagem e Programação</td>
                <td>2025.1</td>
            </tr>
            <tr>
                <td>MAT4001</td>
                <td>Nivelamento de Matemática 1</td>
                <td>2025.1</td>
            </tr>
            <tr>
                <td>ENG4021</td>
                <td>Projeto de Software</td>
                <td>2025.2</td>
            </tr>
            <tr>
                <td>MAT4161</td>
                <td>Cálculo de Uma Variável</td>
                <td>2025.2</td>
            </tr>
        </tbody>
        <tfoot>
        </tfoot>
    </table>
    <h3>Habilidades</h3>
    <ul>
        <li>Logística</li>
        <li>Criatividade</li>
        <li>Gestão de projetos</li>
        <li>Planejamento e Organização</li>
        <li>Proatividade e Colaboração</li>
    </ul>

    <footer>
        <nav>
            <a href="http://www.puc-rio.br" target="_blank">PUC-Rio</a> |
                <a href="{% url 'curriculo:curriculo_spiff' %}">Currículo do meu amigo Spiff</a>
        </nav>
    </footer>
    </main>
</body>
</html>

MeuProjeto/MeuSite/curriculo/templates/curriculo/curriculo-spiff.html
<!DOCTYPE html>
<html lang="ptbr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/curriculo.css">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet">
</head>
<body>
    
    <style> 
        body {
    background-color: #000000;
    font-family: 'Orbitron';
}
nav {
    background-color: blue;
}
.navegacao {
   list-style-type: none;
   color: yellow;
   text-decoration: none
}
h1, h2, h3 {
    color: yellow;
    margin-left: 10px;
}
footer {
    color: orange;
}

#sumario {
    color: #00ffff;
    text-align: center;
}
@media(max-width: 768px){
    .container{
        flex-direction: column; 
    }
    nav {
        width: 100%;
        position: unset;
        margin-left: 0px;
    }
}
    </style>
    
    <h1estrelas></h1estrelas> 
    
    <nav>
        <h2>Menu Estelar</h2>
        <ul>
            <li>PUC-Rio</li>
            <li>Resumo</li>
            <li>Habilidades</li>
            <li>Educação</li>
            <li>Idiomas</li>
            <li>Versão 2</li>
            <li>Meu currículo</li>
        </ul>
</nav>

<main>
    <img src='img/spiff.jpeg' alt='Foto do astronauta Spiff em ação'>
    <h1>Astronauta Spiff</h1>
    <h2>O melhor Astronauta</h2>
    <h3>Astronauta Intergalático e Comandante de Missão Solo</h3>
    <p>Um intrépido e imaginativo astronauta com vasta experiência em exploração espacial solo e em missões críticas a planetas inóspitos. Proficiente em pilotagem de naves espaciais de construção própria, análise de fenômenos alienígenas e resolução criativa de problemas em ambientes extraterrestres. Possui um histórico comprovado de descobertas notáveis e encontros (nem sempre amigáveis) com formas de vida alienígenas diversas.</p>
    <p>Várias Expedições (Contínuo)</p>
    
    
    <ol>
        <li>Doutorado em Exploração Interdimensional e Defesa Contra Alienígenas Malignos (Honras Imaginárias)</li>
        <li>Mestrado em Viagem Hiperespacial (com honras)</li>
        <li>Universidade Estelar de Calvin — Ciências da Galáxia</li>
        <li>Academia Estelar de Calvin — Diploma em Engenharia Espacial e Aventuras</li>
        <li> Currículo incluiu estudos avançados em: </li>
    </ol>
    
    <ul>
        <li>Teoria da Propulsão a Jato de Papelão</li>
        <li>Linguística Alienígena Intuitiva</li>
        <li>Táticas de Fuga e Evasão Escolar Espacial</li>
        <li>Astronomia de Quintal Avançada</li>
        <li>Sobrevivência com Lancheiras e Suco de Limão</li>
    </ul>
    
</main>

<nav>
    <a href="http://www.puc-rio.br">PUC-Rio</a>
    <a href="meu-curriculo.html">Meu currículo</a>
    <a href="#resumo">Resumo</a>
</nav>

<section id="resumo">
    Um monte de texto aqui...
</section>

<footer>"Nenhum alienígena fica para trás... porque eu desintegro todos!"</footer>

<table>
    <thead>
        <tr>
            <th>Código da disciplina</th>
            <th>Nome da disciplina</th>
            <th>Ano e semestre</th>
            <th>Nome do professor</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>CTC4001</td>
            <td>Modelagem e Programação</td>
            <td>2025.1</td>
            <td>Joísa e Felipe</td>
        </tr>
        <tr>
            <td>ENG4021</td>
            <td>Projeto de Software</td>
            <td>2025.2</td>
            <td>Alexandre</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td>MAT4001</td>
            <td>Nivelamento de Matemática 1</td>
            <td>2025.1</td>
            <td>Luís</td>
        </tr>
    </tfoot>
</table>

<ul class="navegacao">
    <li><a href="http://www.puc-rio.br">PUC-Rio</a></li>
    <li><a href="#resumo">Resumo</a></li>
    <!-- outros links -->
</ul>
</body>
</html>